import { PatientScreening } from './types';

export const INITIAL_PATIENTS: PatientScreening[] = [
  {
    id: 'pt-001',
    hn: '67-00101',
    villageNo: '2',
    villageName: 'บ้านนาเดื่อ',
    houseNo: '45/1',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'สมหมาย',
    lastName: 'วงค์อินทร์',
    gender: 'ชาย',
    ageYears: 58,
    ageMonths: 4,
    birthDate: '1968-05-12',
    idCard: '3470500123451',
    phone: '081-456-7890',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ความดันโลหิตสูง',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 09:30',
    heightCm: 168,
    weightKg: 68,
    waistInch: 33,
    waistCm: 84,
    bloodPressureSys: 128,
    bloodPressureDia: 82,
    bmi: 24.1,
    fitResult: 'positive',
    testedDate: '2026-09-11 10:15',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'พบแถบสีแดง 2 ขีด ชัดเจน (Positive)',
    referral: {
      referralNo: 'PNK-REF-2569-001',
      destinationHospital: 'โรงพยาบาลสกลนคร',
      department: 'ศูนย์ส่องกล้องระบบทางเดินอาหาร (Endoscopy Unit)',
      appointmentDate: '2026-09-28',
      appointmentTime: '08:30',
      referralReason: 'ตรวจคัดกรองมะเร็งลำไส้ใหญ่ด้วยวิธี FIT Test ได้ผลบวก (Positive Code 1B0061)',
      referralDoctor: 'นพ.อภิชาติ ปัญญาเลิศ (ว.45892)',
      bowelPrepInstruction: 'รับยาระบาย Swiff/Klean-Prep ตามใบคำแนะนำ งดอาหารกากใย 3 วันก่อนวันนัด และงดน้ำงดอาหารหลังเที่ยงคืน',
      status: 'referred',
      createdDate: '2026-09-12 14:00'
    },
    caTracking: {
      status: 'scheduled',
      fitPositiveDate: '2026-09-11',
      contactDate: '2026-09-12 14:00',
      contactOfficer: 'นายเอกพันธ์ ขันติ (นวก.สาธารณสุข)',
      contactNotes: 'โทรแจ้งผลบวก ผู้ป่วยเข้าใจดี ยินยอมตรวจส่องกล้อง',
      callLogs: [
        {
          id: 'call-1',
          date: '2026-09-12 14:00',
          caller: 'นายเอกพันธ์ ขันติ',
          phone: '081-456-7890',
          outcome: 'answered_agreed',
          notes: 'แจ้งผล FIT Positive แนะนำกระบวนการส่องกล้อง ผู้ป่วยยินยอมให้นัดตรวจ'
        }
      ],
      appointmentDate: '2026-09-28',
      appointmentTime: '08:30',
      hospitalName: 'โรงพยาบาลสกลนคร',
      department: 'ศูนย์ส่องกล้องระบบทางเดินอาหาร (Endoscopy Unit)',
      bowelPrepStatus: 'received_meds',
      bowelPrepNotes: 'รับยาระบาย Swiff 2 ขวด พร้อมเอกสารคำแนะนำแล้ว แนะนำงดอาหารกากใย 3 วันก่อนตรวจ',
      companionName: 'นางมาลี วงค์อินทร์ (ภรรยา)',
      companionPhone: '089-876-5432',
      clinicalNotes: 'มีประวัติความดันโลหิตสูง ควบคุมได้ดี ไม่ได้รับประทานยาละลายลิ่มเลือด'
    }
  },
  {
    id: 'pt-002',
    hn: '67-00102',
    villageNo: '2',
    villageName: 'บ้านนาเดื่อ',
    houseNo: '12',
    subdistrict: 'นาแก้ว',
    prefix: 'นาง',
    firstName: 'ทองสุข',
    lastName: 'บุญมี',
    gender: 'หญิง',
    ageYears: 62,
    ageMonths: 1,
    birthDate: '1964-08-05',
    idCard: '3470500123460',
    phone: '086-123-4567',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'เบาหวานชนิดที่ 2',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 09:45',
    heightCm: 155,
    weightKg: 54,
    waistInch: 30,
    waistCm: 76,
    bloodPressureSys: 120,
    bloodPressureDia: 75,
    bmi: 22.5,
    fitResult: 'negative',
    testedDate: '2026-09-11 10:20',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'ผลตรวจเป็นลบ (Negative 1B0060) นัดตรวจซ้ำอีก 2 ปี'
  },
  {
    id: 'pt-003',
    hn: '67-00103',
    villageNo: '2',
    villageName: 'บ้านนาเดื่อ',
    houseNo: '88/3',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'ประเสริฐ',
    lastName: 'ชัยศรี',
    gender: 'ชาย',
    ageYears: 65,
    ageMonths: 8,
    birthDate: '1961-01-14',
    idCard: '3470500123478',
    phone: '085-789-0123',
    benefitCode: 'OFC',
    benefitName: 'ข้าราชการ/เบิกตรง',
    underlyingDisease: 'ไขมันในเลือดสูง',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 10:00',
    heightCm: 172,
    weightKg: 75,
    waistInch: 34,
    waistCm: 86,
    bloodPressureSys: 135,
    bloodPressureDia: 85,
    bmi: 25.4,
    fitResult: 'negative',
    testedDate: '2026-09-11 10:25',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'ผลตรวจเป็นลบ (Negative 1B0060)'
  },
  {
    id: 'pt-004',
    hn: '67-00104',
    villageNo: '2',
    villageName: 'บ้านนาเดื่อ',
    houseNo: '104',
    subdistrict: 'นาแก้ว',
    prefix: 'นาง',
    firstName: 'สมบูรณ์',
    lastName: 'แก้วเจริญ',
    gender: 'หญิง',
    ageYears: 53,
    ageMonths: 11,
    birthDate: '1972-10-20',
    idCard: '3470500123486',
    phone: '089-234-5678',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 10:15',
    heightCm: 158,
    weightKg: 62,
    waistInch: 32,
    waistCm: 81,
    bloodPressureSys: 118,
    bloodPressureDia: 76,
    bmi: 24.8,
    fitResult: 'positive',
    testedDate: '2026-09-11 10:30',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'Positive ชัดเจน รอส่งต่อตรวจส่องกล้อง',
    caTracking: {
      status: 'pending_contact',
      fitPositiveDate: '2026-09-11',
      callLogs: [
        {
          id: 'call-2',
          date: '2026-09-14 10:30',
          caller: 'นายเอกพันธ์ ขันติ',
          phone: '089-234-5678',
          outcome: 'no_answer',
          notes: 'โทรครั้งที่ 1 สัญญาณติดแต่ไม่มีผู้รับสาย'
        }
      ],
      clinicalNotes: '⚠️ เกินกำหนด 7 วันยังไม่สามารถติดต่อยืนยันวันนัดได้ ประสาน อสม. ม.2 (นางพยอม) ช่วยติดตามที่บ้าน'
    }
  },
  {
    id: 'pt-005',
    hn: '67-00105',
    villageNo: '3',
    villageName: 'บ้านกลาง',
    houseNo: '23',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'บุญเลิศ',
    lastName: 'ศิริรัตน์',
    gender: 'ชาย',
    ageYears: 59,
    ageMonths: 3,
    birthDate: '1967-06-18',
    idCard: '3470500123494',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 10:30',
    heightCm: 165,
    weightKg: 60,
    waistInch: 31,
    waistCm: 79,
    bloodPressureSys: 124,
    bloodPressureDia: 80,
    bmi: 22.0,
    fitResult: 'negative',
    testedDate: '2026-09-11 10:35',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A'
  },
  {
    id: 'pt-006',
    hn: '67-00106',
    villageNo: '3',
    villageName: 'บ้านกลาง',
    houseNo: '56/1',
    subdistrict: 'นาแก้ว',
    prefix: 'นางสาว',
    firstName: 'พรรณี',
    lastName: 'จันทรโชติ',
    gender: 'หญิง',
    ageYears: 51,
    ageMonths: 7,
    birthDate: '1975-02-14',
    idCard: '3470500123508',
    benefitCode: 'SSS',
    benefitName: 'ประกันสังคม',
    underlyingDisease: 'ภูมิแพ้',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 10:45',
    heightCm: 160,
    weightKg: 58,
    waistInch: 29,
    waistCm: 74,
    bloodPressureSys: 115,
    bloodPressureDia: 74,
    bmi: 22.7,
    fitResult: 'inconclusive',
    testedDate: '2026-09-11 10:40',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'ตัวอย่างสิ่งส่งตรวจไม่สมบูรณ์ แถบ Control ไม่ปรากฏ (Inconclusive) จ่ายชุดตรวจใหม่ให้เก็บซ้ำ'
  },
  {
    id: 'pt-007',
    hn: '67-00107',
    villageNo: '10',
    villageName: 'บ้านกลางใหม่',
    houseNo: '15/2',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'วีระ',
    lastName: 'สิทธิชัย',
    gender: 'ชาย',
    ageYears: 67,
    ageMonths: 2,
    birthDate: '1959-07-09',
    idCard: '3470500123516',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ความดันโลหิตสูง, เก๊าท์',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-11 08:30',
    heightCm: 167,
    weightKg: 65,
    waistInch: 33,
    waistCm: 84,
    bloodPressureSys: 130,
    bloodPressureDia: 84,
    bmi: 23.3,
    fitResult: 'negative',
    testedDate: '2026-09-11 11:00',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A'
  },
  {
    id: 'pt-008',
    hn: '67-00108',
    villageNo: '10',
    villageName: 'บ้านกลางใหม่',
    houseNo: '79',
    subdistrict: 'นาแก้ว',
    prefix: 'นาง',
    firstName: 'บัวลอย',
    lastName: 'สายทอง',
    gender: 'หญิง',
    ageYears: 60,
    ageMonths: 5,
    birthDate: '1966-04-12',
    idCard: '3470500123524',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'เบาหวาน',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-11 08:45',
    heightCm: 152,
    weightKg: 50,
    waistInch: 28,
    waistCm: 71,
    bloodPressureSys: 122,
    bloodPressureDia: 78,
    bmi: 21.6,
    fitResult: 'negative',
    testedDate: '2026-09-11 11:05',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A'
  },
  {
    id: 'pt-009',
    hn: '67-00109',
    villageNo: '10',
    villageName: 'บ้านกลางใหม่',
    houseNo: '31',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'สุชาติ',
    lastName: 'บุตรศรี',
    gender: 'ชาย',
    ageYears: 56,
    ageMonths: 9,
    birthDate: '1969-12-03',
    idCard: '3470500123532',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-11 09:00',
    heightCm: 170,
    weightKg: 78,
    waistInch: 35,
    waistCm: 89,
    bloodPressureSys: 138,
    bloodPressureDia: 88,
    bmi: 27.0,
    fitResult: 'positive',
    testedDate: '2026-09-11 11:15',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'Positive ผลบวก มีประวัติถ่ายปนเลือดเป็นครั้งคราว',
    referral: {
      referralNo: 'PNK-REF-2569-003',
      destinationHospital: 'โรงพยาบาลสกลนคร',
      department: 'ศูนย์ส่องกล้องระบบทางเดินอาหาร (Endoscopy Unit)',
      appointmentDate: '2026-10-02',
      appointmentTime: '10:00',
      referralReason: 'ตรวจคัดกรองมะเร็งลำไส้ใหญ่ด้วยวิธี FIT Test ได้ผลบวก (Positive Code 1B0061)',
      referralDoctor: 'นพ.อภิชาติ ปัญญาเลิศ (ว.45892)',
      bowelPrepInstruction: 'รับยาระบาย Swiff/Klean-Prep ตามใบคำแนะนำ งดอาหารกากใย 3 วันก่อนวันนัด',
      status: 'pending_referral',
      createdDate: '2026-09-12 16:00'
    }
  },
  {
    id: 'pt-010',
    hn: '67-00110',
    villageNo: '11',
    villageName: 'บ้านนาเดื่อน้อย',
    houseNo: '92/1',
    subdistrict: 'นาแก้ว',
    prefix: 'นาง',
    firstName: 'มาลี',
    lastName: 'จิตรดี',
    gender: 'หญิง',
    ageYears: 64,
    ageMonths: 3,
    birthDate: '1962-06-25',
    idCard: '3470500123541',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ความดันโลหิตสูง',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-11 09:15',
    heightCm: 154,
    weightKg: 57,
    waistInch: 31,
    waistCm: 79,
    bloodPressureSys: 126,
    bloodPressureDia: 80,
    bmi: 24.0,
    fitResult: 'negative',
    testedDate: '2026-09-11 11:20',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A'
  },
  {
    id: 'pt-011',
    hn: '67-00111',
    villageNo: '11',
    villageName: 'บ้านนาเดื่อน้อย',
    houseNo: '48',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'อนุสรณ์',
    lastName: 'พรหมจักร',
    gender: 'ชาย',
    ageYears: 55,
    ageMonths: 2,
    birthDate: '1971-07-19',
    idCard: '3470500123559',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'received',
    kitReceivedDate: '2026-09-14 09:00',
    heightCm: 169,
    weightKg: 64,
    waistInch: 32,
    waistCm: 81,
    bloodPressureSys: 122,
    bloodPressureDia: 80,
    bmi: 22.4,
    fitResult: 'pending'
  },
  {
    id: 'pt-012',
    hn: '67-00112',
    villageNo: '11',
    villageName: 'บ้านนาเดื่อน้อย',
    houseNo: '65',
    subdistrict: 'นาแก้ว',
    prefix: 'นาง',
    firstName: 'คำมูล',
    lastName: 'แสนสุข',
    gender: 'หญิง',
    ageYears: 68,
    ageMonths: 6,
    birthDate: '1958-03-10',
    idCard: '3470500123567',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'เบาหวาน, ไขมันในเลือดสูง',
    kitStatus: 'received',
    kitReceivedDate: '2026-09-14 09:10',
    heightCm: 150,
    weightKg: 53,
    waistInch: 30,
    waistCm: 76,
    bloodPressureSys: 132,
    bloodPressureDia: 84,
    bmi: 23.6,
    fitResult: 'pending'
  },
  {
    id: 'pt-013',
    hn: '67-00113',
    villageNo: '2',
    villageName: 'บ้านนาเดื่อ',
    houseNo: '11/1',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'ณรงค์',
    lastName: 'สุริยงค์',
    gender: 'ชาย',
    ageYears: 61,
    ageMonths: 4,
    birthDate: '1965-05-30',
    idCard: '3470500123575',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'not_received',
    fitResult: 'pending'
  },
  {
    id: 'pt-014',
    hn: '67-00114',
    villageNo: '1',
    villageName: 'บ้านโพนนาแก้ว',
    houseNo: '58/2',
    subdistrict: 'นาแก้ว',
    prefix: 'นาง',
    firstName: 'คำมูล',
    lastName: 'มิ่งขวัญ',
    gender: 'หญิง',
    ageYears: 63,
    ageMonths: 2,
    birthDate: '1963-07-15',
    idCard: '3470500123583',
    phone: '087-654-3210',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'เบาหวานชนิดที่ 2',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-04 09:00',
    fitResult: 'positive',
    testedDate: '2026-09-05 11:00',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'พบเลือดแฝงในอุจจาระชัดเจน ส่งส่องกล้องแล้ว',
    caTracking: {
      status: 'biopsy_reported',
      fitPositiveDate: '2026-09-05',
      contactDate: '2026-09-06 10:00',
      contactOfficer: 'นายเอกพันธ์ ขันติ',
      contactNotes: 'ประสานนัดด่วนรพ.สกลนคร ผู้ป่วยและญาติพร้อมรับการตรวจ',
      appointmentDate: '2026-09-15',
      appointmentTime: '08:30',
      hospitalName: 'โรงพยาบาลสกลนคร',
      department: 'ศูนย์ส่องกล้องระบบทางเดินอาหาร',
      bowelPrepStatus: 'prep_completed',
      bowelPrepNotes: 'เตรียมลำไส้สะอาดดีมาก (Boston Bowel Prep Score = 8)',
      colonoscopyDate: '2026-09-15',
      colonoscopyHospital: 'โรงพยาบาลสกลนคร',
      colonoscopyDoctor: 'นพ.อภิชาติ ปัญญาเลิศ',
      colonoscopyFinding: 'polyps_removed',
      colonoscopyDetails: 'พบ Sessile polyp ขนาด 1.2 cm ที่ Sigmoid colon และ Pedunculated polyp ขนาด 0.8 cm ที่ Ascending colon ทำ Polypectomy ตัดออกได้ทั้งหมด ไม่มีภาวะแทรกซ้อน',
      polypCount: 2,
      polypSizeLocation: 'Sigmoid colon (1.2 cm) และ Ascending colon (0.8 cm)',
      biopsyDate: '2026-09-20',
      biopsyResult: 'tubular_adenoma',
      biopsyDetails: 'ผลพยาธิวิทยา: Tubular adenoma with low-grade dysplasia, surgical margins are free of dysplasia',
      treatmentPlan: 'แนะนำตรวจส่องกล้องซ้ำ (Surveillance Colonoscopy) ในอีก 3 ปี พร้อมดูแลสุขภาพสม่ำเสมอ',
      clinicalNotes: 'ผู้ป่วยฟื้นตัวดีมาก ไม่มีอาการปวดท้องหรือถ่ายเป็นเลือด ให้คำแนะนำเรื่องอาหารกากใย'
    }
  },
  {
    id: 'pt-015',
    hn: '67-00115',
    villageNo: '5',
    villageName: 'บ้านหนองหวาย',
    houseNo: '19',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'วิชัย',
    lastName: 'อุ่นแสง',
    gender: 'ชาย',
    ageYears: 56,
    ageMonths: 9,
    birthDate: '1969-12-04',
    idCard: '3470500123591',
    phone: '084-555-1234',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'tested',
    fitResult: 'positive',
    testedDate: '2026-09-18 10:40',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609B',
    notes: 'Positive พบ 2 ขีด แจ้งเจ้าหน้าที่ติดตามด่วน',
    caTracking: {
      status: 'contacted',
      fitPositiveDate: '2026-09-18',
      contactDate: '2026-09-19 13:30',
      contactOfficer: 'นายเอกพันธ์ ขันติ',
      contactNotes: 'โทรแจ้งผลบวก ผู้ป่วยรับทราบและยินยอมตรวจ อยู่ระหว่างประสานคิวนัดศูนย์ส่องกล้อง รพ.สกลนคร',
      callLogs: [
        {
          id: 'call-15',
          date: '2026-09-19 13:30',
          caller: 'นายเอกพันธ์ ขันติ',
          phone: '084-555-1234',
          outcome: 'answered_agreed',
          notes: 'รับสาย ยินยอมตรวจส่องกล้อง ขอนัดช่วงปลายเดือนหรือต้นเดือนหน้า'
        }
      ],
      clinicalNotes: 'รอทาง รพ.สกลนคร ยืนยันคิวนัดตรวจส่องกล้องประจำสัปดาห์ถัดไป'
    }
  },
  {
    id: 'pt-016',
    hn: '67-00116',
    villageNo: '4',
    villageName: 'บ้านโพนแคใต้',
    houseNo: '102',
    subdistrict: 'นาแก้ว',
    prefix: 'นาง',
    firstName: 'คำผิว',
    lastName: 'ศรีบุญมี',
    gender: 'หญิง',
    ageYears: 66,
    ageMonths: 5,
    birthDate: '1960-04-18',
    idCard: '3470500123605',
    phone: '082-999-4455',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ข้อเข่าเสื่อม, ความดันโลหิตสูง',
    kitStatus: 'tested',
    fitResult: 'positive',
    testedDate: '2026-09-10 14:20',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'Positive แจ้งเตือนผู้ป่วยปฏิเสธ',
    caTracking: {
      status: 'refused',
      fitPositiveDate: '2026-09-10',
      contactDate: '2026-09-13 11:00',
      contactOfficer: 'นายเอกพันธ์ ขันติ',
      contactNotes: 'ผู้ป่วยแจ้งว่ากลัวเจ็บมาก และไม่มีญาติพาไป รพ.สกลนคร จึงขอปฏิเสธการส่องกล้อง',
      callLogs: [
        {
          id: 'call-16',
          date: '2026-09-13 11:00',
          caller: 'นายเอกพันธ์ ขันติ',
          phone: '082-999-4455',
          outcome: 'answered_refused',
          notes: 'ให้ข้อมูลเรื่องยาระงับความรู้สึกและการดูแล แต่ผู้ป่วยยังยืนยันปฏิเสธ'
        }
      ],
      clinicalNotes: 'ผู้ป่วยปฏิเสธการส่องกล้อง อธิบายความเสี่ยงเรื่องมะเร็งระยะเริ่มต้นแล้วยังไม่ยินยอม ประสานทีมหมอครอบครัวและ อสม. ร่วมลงเยี่ยมบ้านให้กำลังใจและสร้างความเข้าใจเพิ่มเติม'
    }
  },
  {
    id: 'pt-017',
    hn: '67-00117',
    villageNo: '8',
    villageName: 'บ้านท่าแร่ใต้',
    houseNo: '33',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'ประดิษฐ์',
    lastName: 'คำภา',
    gender: 'ชาย',
    ageYears: 59,
    ageMonths: 1,
    birthDate: '1967-08-22',
    idCard: '3470500123613',
    phone: '090-333-6677',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'tested',
    fitResult: 'positive',
    testedDate: '2026-09-09 09:15',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'Positive 2 ขีดชัดเจน โทรติดต่อไม่ได้ 3 ครั้ง',
    caTracking: {
      status: 'cannot_contact',
      fitPositiveDate: '2026-09-09',
      callLogs: [
        {
          id: 'call-17a',
          date: '2026-09-11 09:30',
          caller: 'นายเอกพันธ์ ขันติ',
          phone: '090-333-6677',
          outcome: 'no_answer',
          notes: 'ไม่มีผู้รับสาย'
        },
        {
          id: 'call-17b',
          date: '2026-09-13 14:00',
          caller: 'นายเอกพันธ์ ขันติ',
          phone: '090-333-6677',
          outcome: 'no_answer',
          notes: 'ปิดเครื่อง/ไม่สามารถติดต่อได้'
        },
        {
          id: 'call-17c',
          date: '2026-09-16 10:15',
          caller: 'นายเอกพันธ์ ขันติ',
          phone: '090-333-6677',
          outcome: 'no_answer',
          notes: 'โทรไม่ติด ติดต่อไม่ได้'
        }
      ],
      clinicalNotes: '⚠️ เกินกำหนด 7 วัน โทร 3 ครั้งไม่สามารถติดต่อได้ ส่งรายชื่อให้ รพ.สต. และ อสม. ม.8 ติดตามตัวผู้ป่วยที่บ้านโดยตรง'
    }
  }
];

export { VILLAGE_LIST, PHON_NA_KAEO_VILLAGES, SUBDISTRICT_LIST, HEALTH_CENTER_LIST } from './data/villages';
