import { PatientScreening } from './types';

export const INITIAL_PATIENTS: PatientScreening[] = [
  {
    id: 'pt-001',
    hn: '67-00101',
    villageNo: '1',
    villageName: 'บ้านโพนนาแก้ว',
    houseNo: '45/1',
    subdistrict: 'โพนนาแก้ว',
    prefix: 'นาย',
    firstName: 'สมหมาย',
    lastName: 'วงค์อินทร์',
    gender: 'ชาย',
    ageYears: 58,
    ageMonths: 4,
    birthDate: '1968-05-12',
    idCard: '3470500123451',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ความดันโลหิตสูง',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 09:30',
    heightCm: 168,
    weightKg: 68,
    waistInch: 33,
    waistCm: 84,
    bloodPressureSys: 128,
    bloodPressureDia: 82,
    bmi: 24.1,
    fitResult: 'positive',
    testedDate: '2026-09-11 10:15',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'พบแถบสีแดง 2 ขีด ชัดเจน (Positive)',
    referral: {
      referralNo: 'PNK-REF-2569-001',
      destinationHospital: 'โรงพยาบาลสกลนคร',
      department: 'ศูนย์ส่องกล้องระบบทางเดินอาหาร (Endoscopy Unit)',
      appointmentDate: '2026-09-28',
      appointmentTime: '08:30',
      referralReason: 'ตรวจคัดกรองมะเร็งลำไส้ใหญ่ด้วยวิธี FIT Test ได้ผลบวก (Positive Code 1B0061)',
      referralDoctor: 'นพ.อภิชาติ ปัญญาเลิศ (ว.45892)',
      bowelPrepInstruction: 'รับยาระบาย Swiff/Klean-Prep ตามใบคำแนะนำ งดอาหารกากใย 3 วันก่อนวันนัด และงดน้ำงดอาหารหลังเที่ยงคืน',
      status: 'referred',
      createdDate: '2026-09-12 14:00'
    }
  },
  {
    id: 'pt-002',
    hn: '67-00102',
    villageNo: '1',
    villageName: 'บ้านโพนนาแก้ว',
    houseNo: '12',
    subdistrict: 'โพนนาแก้ว',
    prefix: 'นาง',
    firstName: 'ทองสุข',
    lastName: 'บุญมี',
    gender: 'หญิง',
    ageYears: 62,
    ageMonths: 1,
    birthDate: '1964-08-05',
    idCard: '3470500123460',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'เบาหวานชนิดที่ 2',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 09:45',
    heightCm: 155,
    weightKg: 54,
    waistInch: 30,
    waistCm: 76,
    bloodPressureSys: 120,
    bloodPressureDia: 75,
    bmi: 22.5,
    fitResult: 'negative',
    testedDate: '2026-09-11 10:20',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'ผลตรวจเป็นลบ (Negative 1B0060) นัดตรวจซ้ำอีก 2 ปี'
  },
  {
    id: 'pt-003',
    hn: '67-00103',
    villageNo: '2',
    villageName: 'บ้านนาแก้ว',
    houseNo: '88/3',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'ประเสริฐ',
    lastName: 'ชัยศรี',
    gender: 'ชาย',
    ageYears: 65,
    ageMonths: 8,
    birthDate: '1961-01-14',
    idCard: '3470500123478',
    benefitCode: 'OFC',
    benefitName: 'ข้าราชการ/เบิกตรง',
    underlyingDisease: 'ไขมันในเลือดสูง',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 10:00',
    heightCm: 172,
    weightKg: 75,
    waistInch: 34,
    waistCm: 86,
    bloodPressureSys: 135,
    bloodPressureDia: 85,
    bmi: 25.4,
    fitResult: 'negative',
    testedDate: '2026-09-11 10:25',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'ผลตรวจเป็นลบ (Negative 1B0060)'
  },
  {
    id: 'pt-004',
    hn: '67-00104',
    villageNo: '2',
    villageName: 'บ้านนาแก้ว',
    houseNo: '104',
    subdistrict: 'นาแก้ว',
    prefix: 'นาง',
    firstName: 'สมบูรณ์',
    lastName: 'แก้วเจริญ',
    gender: 'หญิง',
    ageYears: 53,
    ageMonths: 11,
    birthDate: '1972-10-20',
    idCard: '3470500123486',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 10:15',
    heightCm: 158,
    weightKg: 62,
    waistInch: 32,
    waistCm: 81,
    bloodPressureSys: 118,
    bloodPressureDia: 76,
    bmi: 24.8,
    fitResult: 'positive',
    testedDate: '2026-09-11 10:30',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'Positive ชัดเจน แนะนำส่งส่องกล้อง',
    referral: {
      referralNo: 'PNK-REF-2569-002',
      destinationHospital: 'โรงพยาบาลสกลนคร',
      department: 'ศูนย์ส่องกล้องระบบทางเดินอาหาร (Endoscopy Unit)',
      appointmentDate: '2026-09-30',
      appointmentTime: '09:00',
      referralReason: 'ตรวจคัดกรองมะเร็งลำไส้ใหญ่ด้วยวิธี FIT Test ได้ผลบวก (Positive Code 1B0061)',
      referralDoctor: 'พญ.ชลธิชา มั่นคง (ว.51204)',
      bowelPrepInstruction: 'รับยาระบาย Swiff/Klean-Prep ตามคู่มือ งดผักผลไม้เมล็ดพืช 3 วันก่อนตรวจ',
      status: 'pending_referral',
      createdDate: '2026-09-12 15:30'
    }
  },
  {
    id: 'pt-005',
    hn: '67-00105',
    villageNo: '3',
    villageName: 'บ้านหนองกระบอก',
    houseNo: '23',
    subdistrict: 'นาแก้ว',
    prefix: 'นาย',
    firstName: 'บุญเลิศ',
    lastName: 'ศิริรัตน์',
    gender: 'ชาย',
    ageYears: 59,
    ageMonths: 3,
    birthDate: '1967-06-18',
    idCard: '3470500123494',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 10:30',
    heightCm: 165,
    weightKg: 60,
    waistInch: 31,
    waistCm: 79,
    bloodPressureSys: 124,
    bloodPressureDia: 80,
    bmi: 22.0,
    fitResult: 'negative',
    testedDate: '2026-09-11 10:35',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A'
  },
  {
    id: 'pt-006',
    hn: '67-00106',
    villageNo: '3',
    villageName: 'บ้านหนองกระบอก',
    houseNo: '56/1',
    subdistrict: 'นาแก้ว',
    prefix: 'นางสาว',
    firstName: 'พรรณี',
    lastName: 'จันทรโชติ',
    gender: 'หญิง',
    ageYears: 51,
    ageMonths: 7,
    birthDate: '1975-02-14',
    idCard: '3470500123508',
    benefitCode: 'SSS',
    benefitName: 'ประกันสังคม',
    underlyingDisease: 'ภูมิแพ้',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-10 10:45',
    heightCm: 160,
    weightKg: 58,
    waistInch: 29,
    waistCm: 74,
    bloodPressureSys: 115,
    bloodPressureDia: 74,
    bmi: 22.7,
    fitResult: 'inconclusive',
    testedDate: '2026-09-11 10:40',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'ตัวอย่างสิ่งส่งตรวจไม่สมบูรณ์ แถบ Control ไม่ปรากฏ (Inconclusive) จ่ายชุดตรวจใหม่ให้เก็บซ้ำ'
  },
  {
    id: 'pt-007',
    hn: '67-00107',
    villageNo: '4',
    villageName: 'บ้านนาปลาโหล',
    houseNo: '15/2',
    subdistrict: 'นาปลาโหล',
    prefix: 'นาย',
    firstName: 'วีระ',
    lastName: 'สิทธิชัย',
    gender: 'ชาย',
    ageYears: 67,
    ageMonths: 2,
    birthDate: '1959-07-09',
    idCard: '3470500123516',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ความดันโลหิตสูง, เก๊าท์',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-11 08:30',
    heightCm: 167,
    weightKg: 65,
    waistInch: 33,
    waistCm: 84,
    bloodPressureSys: 130,
    bloodPressureDia: 84,
    bmi: 23.3,
    fitResult: 'negative',
    testedDate: '2026-09-11 11:00',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A'
  },
  {
    id: 'pt-008',
    hn: '67-00108',
    villageNo: '4',
    villageName: 'บ้านนาปลาโหล',
    houseNo: '79',
    subdistrict: 'นาปลาโหล',
    prefix: 'นาง',
    firstName: 'บัวลอย',
    lastName: 'สายทอง',
    gender: 'หญิง',
    ageYears: 60,
    ageMonths: 5,
    birthDate: '1966-04-12',
    idCard: '3470500123524',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'เบาหวาน',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-11 08:45',
    heightCm: 152,
    weightKg: 50,
    waistInch: 28,
    waistCm: 71,
    bloodPressureSys: 122,
    bloodPressureDia: 78,
    bmi: 21.6,
    fitResult: 'negative',
    testedDate: '2026-09-11 11:05',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A'
  },
  {
    id: 'pt-009',
    hn: '67-00109',
    villageNo: '5',
    villageName: 'บ้านดอนกอย',
    houseNo: '31',
    subdistrict: 'เชียงสือ',
    prefix: 'นาย',
    firstName: 'สุชาติ',
    lastName: 'บุตรศรี',
    gender: 'ชาย',
    ageYears: 56,
    ageMonths: 9,
    birthDate: '1969-12-03',
    idCard: '3470500123532',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-11 09:00',
    heightCm: 170,
    weightKg: 78,
    waistInch: 35,
    waistCm: 89,
    bloodPressureSys: 138,
    bloodPressureDia: 88,
    bmi: 27.0,
    fitResult: 'positive',
    testedDate: '2026-09-11 11:15',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A',
    notes: 'Positive ผลบวก มีประวัติถ่ายปนเลือดเป็นครั้งคราว',
    referral: {
      referralNo: 'PNK-REF-2569-003',
      destinationHospital: 'โรงพยาบาลสกลนคร',
      department: 'ศูนย์ส่องกล้องระบบทางเดินอาหาร (Endoscopy Unit)',
      appointmentDate: '2026-10-02',
      appointmentTime: '10:00',
      referralReason: 'ตรวจคัดกรองมะเร็งลำไส้ใหญ่ด้วยวิธี FIT Test ได้ผลบวก (Positive Code 1B0061)',
      referralDoctor: 'นพ.อภิชาติ ปัญญาเลิศ (ว.45892)',
      bowelPrepInstruction: 'รับยาระบาย Swiff/Klean-Prep ตามใบคำแนะนำ งดอาหารกากใย 3 วันก่อนวันนัด',
      status: 'pending_referral',
      createdDate: '2026-09-12 16:00'
    }
  },
  {
    id: 'pt-010',
    hn: '67-00110',
    villageNo: '5',
    villageName: 'บ้านดอนกอย',
    houseNo: '92/1',
    subdistrict: 'เชียงสือ',
    prefix: 'นาง',
    firstName: 'มาลี',
    lastName: 'จิตรดี',
    gender: 'หญิง',
    ageYears: 64,
    ageMonths: 3,
    birthDate: '1962-06-25',
    idCard: '3470500123541',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ความดันโลหิตสูง',
    kitStatus: 'tested',
    kitReceivedDate: '2026-09-11 09:15',
    heightCm: 154,
    weightKg: 57,
    waistInch: 31,
    waistCm: 79,
    bloodPressureSys: 126,
    bloodPressureDia: 80,
    bmi: 24.0,
    fitResult: 'negative',
    testedDate: '2026-09-11 11:20',
    testedBy: 'ทนพญ.กนกพร (ห้องปฏิบัติการ)',
    testLotNo: 'FIT-202609A'
  },
  {
    id: 'pt-011',
    hn: '67-00111',
    villageNo: '6',
    villageName: 'บ้านดงมะไฟ',
    houseNo: '48',
    subdistrict: 'โพนนาแก้ว',
    prefix: 'นาย',
    firstName: 'อนุสรณ์',
    lastName: 'พรหมจักร',
    gender: 'ชาย',
    ageYears: 55,
    ageMonths: 2,
    birthDate: '1971-07-19',
    idCard: '3470500123559',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'received',
    kitReceivedDate: '2026-09-14 09:00',
    heightCm: 169,
    weightKg: 64,
    waistInch: 32,
    waistCm: 81,
    bloodPressureSys: 122,
    bloodPressureDia: 80,
    bmi: 22.4,
    fitResult: 'pending'
  },
  {
    id: 'pt-012',
    hn: '67-00112',
    villageNo: '6',
    villageName: 'บ้านดงมะไฟ',
    houseNo: '65',
    subdistrict: 'โพนนาแก้ว',
    prefix: 'นาง',
    firstName: 'คำมูล',
    lastName: 'แสนสุข',
    gender: 'หญิง',
    ageYears: 68,
    ageMonths: 6,
    birthDate: '1958-03-10',
    idCard: '3470500123567',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'เบาหวาน, ไขมันในเลือดสูง',
    kitStatus: 'received',
    kitReceivedDate: '2026-09-14 09:10',
    heightCm: 150,
    weightKg: 53,
    waistInch: 30,
    waistCm: 76,
    bloodPressureSys: 132,
    bloodPressureDia: 84,
    bmi: 23.6,
    fitResult: 'pending'
  },
  {
    id: 'pt-013',
    hn: '67-00113',
    villageNo: '7',
    villageName: 'บ้านหนองผือ',
    houseNo: '11/1',
    subdistrict: 'โพนนาแก้ว',
    prefix: 'นาย',
    firstName: 'ณรงค์',
    lastName: 'สุริยงค์',
    gender: 'ชาย',
    ageYears: 61,
    ageMonths: 4,
    birthDate: '1965-05-30',
    idCard: '3470500123575',
    benefitCode: 'UCS',
    benefitName: 'บัตรทอง (UC)',
    underlyingDisease: 'ไม่มี',
    kitStatus: 'not_received',
    fitResult: 'pending'
  }
];

export const VILLAGE_LIST = [
  { no: '1', name: 'บ้านโพนนาแก้ว', subdistrict: 'โพนนาแก้ว' },
  { no: '2', name: 'บ้านนาแก้ว', subdistrict: 'นาแก้ว' },
  { no: '3', name: 'บ้านหนองกระบอก', subdistrict: 'นาแก้ว' },
  { no: '4', name: 'บ้านนาปลาโหล', subdistrict: 'นาปลาโหล' },
  { no: '5', name: 'บ้านดอนกอย', subdistrict: 'เชียงสือ' },
  { no: '6', name: 'บ้านดงมะไฟ', subdistrict: 'โพนนาแก้ว' },
  { no: '7', name: 'บ้านหนองผือ', subdistrict: 'โพนนาแก้ว' },
  { no: '8', name: 'บ้านสร้างแก้ว', subdistrict: 'นาปลาโหล' }
];
